import { v4 as uuidv4 } from 'uuid';
export const data = [
  {
    id: '1',
    Task: 'Brainstorming',
    // Assigned_To: 'Beltran',
    // Assignee: 'Romona',
    // Status: 'To-do',
    detail:'Brainstorming brings team members diverse experience into play. ',
    Priority: 'Low',
    Due_Date: '25-May-2020',
    comments: 9,
    file:10,
  },
  {
    id: '2',
    Task: 'Research',
    // Assigned_To: 'Dave',
    // Assignee: 'Romona',
    // Status: 'To-do',
    detail:"User research helps you to create an optimal product for users. ",
    Priority: 'Low',
    Due_Date: '26-May-2020',
    comments: 10,
    file:3,
  },
  {
    id: '3',
    Task: 'Wireframes',
    // Assigned_To: 'Roman',
    // Assignee: 'Romona',
    // Status: 'To-do',
    detail:"Low fidelity wireframes include the most basic content and visuals. ",
    Priority: 'Low',
    Due_Date: '27-May-2020',
    comments: 2,
    file:0,
  },
  {
    id: '4',
    Task: 'Mockup',
    // Assigned_To: 'Gawen',
    // Assignee: 'Kai',
    // Status: 'Done',
    detail:"Low fidelity mockup include the most basic content and visuals.",
    Priority: 'High',
    Due_Date: '23-Aug-2020',
    comments: 4,
    file:1,
  },
 
  
  

 
];

export const columnsFromBackend = {
  [uuidv4()]: {
    title: 'To-do',
    items: data,
  },
  [uuidv4()]: {
    title: 'On Progress',
    items: [{
      id: '7',
      Task: 'Onboarding Illustrations ',
      // Assigned_To: 'Bondon',
      // Assignee: 'Antoinette',
      // Status: 'In Progress',
      img:"https://kanban-19hrlu0a9-chintansheth2001.vercel.app/assets/cardi1-31c77e9b.png",
      Priority: 'completed',
      // Due_Date: '05-Jan-2021',
      comments: 14,
      file:15,
    },
    {
      id: '6',
      Task: 'Moodboard',
      // Assigned_To: 'Bondon',
      // Assignee: 'Antoinette',
      // Status: 'In Progress',
      Priority: 'completed',
      img:"https://kanban-19hrlu0a9-chintansheth2001.vercel.app/assets/cardi2-e8e6347a.png",
      // Due_Date: '05-Jan-2021',
      comments: 9,
      file:10,
    },
    {
      id: '5',
      Task: 'User Journeys ',
      // Assigned_To: 'Bondon',
      // Assignee: 'Antoinette',
      // Status: 'In Progress',
      detail:"User journeys are the step-by-step journey that a user takes to reach their goal.",
      Priority: 'Medium',
      Due_Date: '05-Jan-2021',
      comments: 8,
      file:20,
    },],
  },
  [uuidv4()]: {
    title: 'Done',
    items: [ {
      id: '9',
      Task: 'Mobile App Design',
      // Assigned_To: 'Bondon',
      // Assignee: 'Antoinette',
      // Status: 'In Progress',
      img:"https://kanban-19hrlu0a9-chintansheth2001.vercel.app/assets/cardi3-6cdb340a.png",
      Priority: 'completed',
      Due_Date: '05-Jan-2021',
      comments: 12,
      file:15,
    },
    {
      id: '8',
      Task: 'Design System',
      // Assigned_To: 'Bondon',
      // Assignee: 'Antoinette',
      // Status: 'In Progress',
      detail:"It just needs to adapt the UI from what you did before ",
      Priority: 'Medium',
      comments: 12,
      file:15,
      Due_Date: '05-Jan-2021',
    },],
  },
};
